language: python

dist: xenial

services:
  - docker

addons:
    apt:
        packages:
            - libxkbcommon-x11-0  # for PyQt 5.12

env:
  global:
    - PYQT_DEPS="PyQt5~=5.12.0 PyQtWebengine~=5.12.0"

matrix:
    include:
        - env: RUN_PYLINT=true
          python: '3.6'
          cache: {}
        - env: BUILD_DOCS=true
          python: '3.6'
          script: source $TRAVIS_BUILD_DIR/.travis/build_doc.sh
        - python: '3.6'
          env:
            - UPLOAD_COVERAGE=true
        - python: '3.7'
          env:
            - PYQT_DEPS="PyQt5~=5.14.0 PyQtWebengine~=5.14.0"
    fast_finish: true

cache:
    apt: true
    pip: true
    ccache: true
    directories:
        - $TRAVIS_BUILD_DIR/postgres
        - $TRAVIS_BUILD_DIR/pyqt

before_cache:

before_install:
    - set -e  # fail on any error
    - source $TRAVIS_BUILD_DIR/.travis/util.sh

install:
    - source $TRAVIS_BUILD_DIR/.travis/stage_install.sh

script:
    - source $TRAVIS_BUILD_DIR/.travis/stage_script.sh

after_success:
    - source $TRAVIS_BUILD_DIR/.travis/stage_after_success.sh
